#!/bin/bash

DIR="COMMITS"
FILE="$DIR/commitInfo.txt"

read -p "Sauvegarde de la base dans ce commit (y/[n]) ?" yn < /dev/tty
yn=${yn:-n}

case $yn in
  [Yy]* )
    mkdir -p "$DIR"
    echo "commit vérifié le $(date '+%Y-%m-%d %H:%M:%S')" > "$FILE"
    git add "$FILE"
    exit 0
    ;;
  [Nn]* )
    exit 0
    ;;
  * )
    exit 0
    ;;
esac